name: Notifier

on:
  push:
    branches: [ tuyen_develop, manh_develop, develop ]


jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      # uses: appleboy/telegram-action@master
      with:
        message: |
          ğŸ™‹â€â™‚ï¸ ${{ github.actor }} created commit:
          ğŸ–¥ Commit message: ${{ github.event.commits[0].message }}
          ğŸ‘¨â€ğŸ’» Repository: ${{ github.repository }}
          ğŸ‘¨â€ğŸ’»ğŸ‘¨â€ğŸ’» Branch: ${{ github.ref }}
          ğŸ‘¨â€ğŸ’»ğŸ‘¨â€ğŸ’»ğŸ‘¨â€ğŸ’» Ref: ${{ github.ref_name }}
          ğŸ“ˆ See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      run: |
        curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' \
        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&&message_thread_id=${{ secrets.TELEGRAM_BOT_TOPIC_ID }}text=${message}"
        