name: Notifier

on:
  push:
    branches: [ tuyen_develop, manh_develop, develop ]


jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: send custom message
      run: |
        msg_text=' ğŸ™‹â€â™‚ï¸ ${{ github.actor }} created commit:\nğŸ–¥ Commit message: ${{ github.event.commits[0].message }}\n ğŸ‘¨â€ğŸ’» Repository: ${{ github.repository }}\n ğŸ‘¨â€ğŸ’»ğŸ‘¨â€ğŸ’» Branch: ${{ github.ref }}\n ğŸ‘¨â€ğŸ’»ğŸ‘¨â€ğŸ’»ğŸ‘¨â€ğŸ’» Ref: ${{ github.ref_name }}\n ğŸ“ˆ See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}'
        curl -s -X POST 'https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage' \
        -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=${msg_text}&message_thread_id=${{ secrets.TELEGRAM_TOPIC_ID }}"
        